services:
  openvscode-server:
    image: ${REGISTRY}/nodejs-workspace
    runtime: crun
    build:
      context: ./
      no_cache: true
    restart: always
    network_mode: host
    privileged: true
    command: sudo chown openvscode-server:openvscode-server /home/workspace/.docker -R
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - type: bind
        source: ${PROJECTS_PATH}
        target: /home/projects
      - type: bind
        source: ${SSH_PATH}
        target: /home/openvscode-server/.ssh
      - type: bind
        source: "/var/run/docker.sock"
        target: /home/workspace/.docker/run/docker.sock
      - type: volume
        source: ovsc_extensions
        target: /home/workspace

volumes:
  ovsc_extensions:
    name: ovsc_extensions
