services:
  gitpod:
    image: ${REGISTRY}/nodejs-workspace
    build:
      context: ./
    restart: always
    runtime: runc
    network_mode: host
    volumes:
      - type: bind
        source: /home/${USER}/${PROJECTS_PATH}
        target: /home/workspace/Projects
      - type: bind
        source: /home/${USER}/.ssh
        target: /home/${USER}/.ssh
      - type: bind
        read_only: true
        source: "/var/run/docker.sock"
        target: /var/run/docker.sock
      - type: volume
        source: ovsc_extensions
        target: /home/workspace/.openvscode-server

volumes:
  ovsc_extensions:
    name: ovsc_extensions
