services:
  gitpod:
    image: ${REGISTRY}/nodejs-workspace
    build:
      context: ./
    restart: always
    runtime: runc
    network_mode: host
    volumes:
      - type: bind
        source: ${PROJECTS_PATH}
        target: /home/workspace:cached
      - type: bind
        source: ${SSH_PATH}
        target: /home/openvscode-server/.ssh
      - type: bind
        source: "/var/run/docker.sock"
        target: /home/workspace/.docker/run/docker.sock
      - type: volume
        source: ovsc_extensions
        target: /home/workspace

volumes:
  ovsc_extensions:
    name: ovsc_extensions
